# Generated by Django 4.0.6 on 2022-07-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_resp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resp',
        ),
    ]
